sqoopTmpDirPrefix: /tmp/sqoop/import
scripts_hdfsDir:
  sqoop: /tmp/scripts/sqoop

oozie_hdfsDir: /tmp/oozie/workflows



#mysql-connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvientionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20





mybatis:
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper-mysql/*.xml,classpath:mapper/*.xml






#------------hive------------
#yarn队列名
HIVE_QUEUE_NAME: default
#hive 计算引擎类型 (0表示Tez，1表示MapReduce)
ENGINE_TYPE: 0
#------------hdfs------------
#hdfs 路径
HDFS_URI: hdfs://localhost:8020
#hdfs 操作用户
HDFS_OPER_USER: hdfs
#------------oozie------------
#oozie提交到集群中的用户
OOZIE_QUEUE_NAME: default
USER_NAME: yarn
BASE_OOZIE_URL: http://cdh01:11000/oozie
OOZIE_USE_SYSTEM_LIBPATH: true
NAMENODE: hdfs://cdh01:8020
JOBTRACKER: cdh01:8032
OOZIE_WF_APPLICATION_PATH: /apps/oozie/workflowXml
OOZIE_COORDINATOR_APPLICATION_PATH: /apps/oozie/coordinatorXml
START_TIME: 2018-10-18T14:10+0800
END_TIME: 2518-10-18T14:10+0800